spring:
  application:
    name: KeyMinter
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: 893760
      timeout: 3000ms
      database: 0
      lettuce:
        pool:
          max-active: 20
          max-wait: -1ms
          max-idle: 10
          min-idle: 0
          time-between-eviction-runs: 30000ms
  datasource:
    url: jdbc:mysql://localhost:3306/chao
    username: root
    password: 893760
    driver-class-name: com.mysql.cj.jdbc.Driver
exception:
  print-method: true

key-minter:
  algorithm: HMAC256
  key-dir: ${user.home}/.keyminter-test-env
  enable-rotation: true
  preferred-key-id: ""
  force-load: true
  export-enabled: false
  metrics-enabled: true
  max-algo-instance: 5
  admin-token: changeme-admin

server:
  port: 8080
