spring:
  application:
    name: KeyMinter
key-minter:
  algorithm: HMAC256
#  key-dir: ${user.home}/demo
  key-dir: D:/Lan/tmp
  enable-rotation: true
  preferred-key-id: ""
  force-load: false
  export-enabled: false
  metrics-enabled: true
